version: '3'
services:
  namesrv:
    build:
      context: ./namesrv
      args:
        - version=4.1.0-incubating
    ports:
      - 9876:9876
    networks:
      - rocketmq
    volumes:
      - rocketmq-namesrv-logs:/opt/logs
      - rocketmq-namesrv-store:/opt/store
  broker:
    build:
      context: ./broker
      args:
        - version=4.1.0-incubating
    ports:
      - 10909:10909
      - 10911:10911
    networks:
      - rocketmq
    volumes:
      - rocketmq-broker-logs:/opt/logs
      - rocketmq-broker-store:/opt/store
    depends_on:
      - namesrv
  console:
    image: styletang/rocketmq-console-ng:latest
    networks:
      - rocketmq
    volumes:
     - /etc/localtime:/etc/localtime:ro
    ports:
     - "18080:8080"
    environment:
     JAVA_OPTS: -Drocketmq.config.namesrvAddr=namesrv:9876
networks:
  rocketmq:
volumes:
  rocketmq-namesrv-logs:
  rocketmq-namesrv-store:
  rocketmq-broker-logs:
  rocketmq-broker-store: